### ISSUE TITLE
Your project is a bit complicated, I can’t understand, can you help me see where I went wrong

### ISSUE THREAD

**Issue by Ran-Xing** [reddec/ssl-cp#2]
https://github.com/XRSec/ssl-tools/blob/dev/sslt.go

**Comment by reddec** [comment]
Tell me please:
- what did you want to do
- what did you expect
- what went wrong

**Comment by Ran-Xing** [comment]
@reddec I want to generate a level 3 certificate:
Root certificate, intermediate certificate, web certificate
But some software requires two certificates, and I am not willing to give them the key of my root certificate, so I want to generate one more certificate


At present, the go program I wrote myself has been able to generate a level 3 certificate, but it seems to be a configuration problem and the certificate chain is wrong.

I am not very mature with the golang language myself. As you can see, I wrote my own code based on the code of [Mattemagikern](https://gist.github.com/Mattemagikern/328cdd650be33bc33105e26db88e487d) and [shaneutt](https://gist.github.com/shaneutt/5e1995295cff6721c89a71d13a71c251).

**Comment by Ran-Xing** [comment]
The certificate problem has bothered me for a long time, thank you very much

**Comment by reddec** [comment]
Root certificate, intermediate certificate, web certificate - ok, got it, pretty straightforward. 
> But some software requires two certificates, and I am not willing to give them the key of my root certificate, so I want to generate one more certificate

This is confusing me - why something requires a private key of root CA? Maybe application expected just web private key (secret part of web certificate pair)

**Comment by Ran-Xing** [comment]
@reddecHave you found anything?
